version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh

    command: sleep infinity

    ports:
      - "80:80"
      - "8080:8080"

    env_file:
      - ../.env

    depends_on:
      - db

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"

  pma: 
    image: phpmyadmin
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - "8082:80"

volumes:
  mariadb-data:
