version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/var/www/html:cached
      - ../.env:/var/www/html/.env

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    ports:
      - "80:80"

    environment:
      DB_HOST: db
      DB_NAME: boardgames_db
      DB_USER: mariadb
      DB_PASS: mariadb
      SITENAME: "Board Games Website"

    depends_on:
      - db

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: boardgames_db
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    ports:
      - "3306:3306"

  pma: 
    image: phpmyadmin
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - "8082:80"

volumes:
  mariadb-data:
