version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/var/www/html:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    ports:
      - "80:80"

    depends_on:
      - db

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  pma: 
    image: phpmyadmin
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8082:80

  
volumes:
  mariadb-data:
